Pass arguments to the run task
modelix/modelix.samples pull request #62
Opened 2023-02-02 14:09 UTC by sergej-koscejev

2023-04-13 09:24 UTC, nkoester requested changes
Thanks for the PR!

Unfortunately, using it as is will fail running the model server from the top-level folder:

```
./gradlew model-server:run

> Task :model-server:run
11:21:12,673 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.6
11:21:12,693 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:21:12,702 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/nkoester/.gradle/caches/modules-2/files-2.1/org.modelix/model-server/2.1.1/65a2639b04f2081e95d73c4da9d94577d91ce66b/model-server-2.1.1.jar!/logback.xml]
11:21:12,706 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@217ed35e - URL [jar:file:/home/nkoester/.gradle/caches/modules-2/files-2.1/org.modelix/model-server/2.1.1/65a2639b04f2081e95d73c4da9d94577d91ce66b/model-server-2.1.1.jar!/logback.xml] is not of type file
11:21:12,790 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [console]
11:21:12,790 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:21:12,797 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:21:12,809 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to DEBUG
11:21:12,811 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [console] to Logger[ROOT]
11:21:12,811 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@59af0466 - End of configuration.
11:21:12,811 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@62230c58 - Registering current configuration as safe fallback point
11:21:12.822 [main] INFO  org.modelix.model.server.Main - Max memory (bytes): 12557746176
11:21:12.823 [main] INFO  org.modelix.model.server.Main - Server process started
11:21:12.824 [main] INFO  org.modelix.model.server.Main - In memory: true
11:21:12.824 [main] INFO  org.modelix.model.server.Main - Path to secret file: /secrets/modelsecret/modelsecret.txt
11:21:12.824 [main] INFO  org.modelix.model.server.Main - Path to JDBC configuration file: null
11:21:12.824 [main] INFO  org.modelix.model.server.Main - Schema initialization: false
11:21:12.825 [main] INFO  org.modelix.model.server.Main - Set values: []
11:21:12.825 [main] INFO  org.modelix.model.server.Main - Port: 28101
11:21:12.826 [main] ERROR org.modelix.model.server.Main -
java.io.FileNotFoundException: courses.modelsever.dump (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileReader.<init>(FileReader.java:75)
        at org.modelix.model.server.Main.main(Main.kt:98)
```

2023-04-22 17:14 UTC, sergej-koscejev commented
I think changing the last argument to `file("courses.modelsever.dump")` should work.

2023-04-27 11:07 UTC, nkoester commented
As it turns out, it was just a typo :sweat_smile:

2023-04-27 11:08 UTC, nkoester approved these changes

2023-04-27 11:09 UTC, merged